In [4]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 72,  84,  86,  94,  55],
       [ 70,  91,  86,  77,  75],
       [ 98,  82,  87,  89,  61],
       [ 90,  69,  93,  85,  50],
       [ 91,  65,  52,  69,  65],
       [ 56,  97,  68,  64,  71],
       [ 73,  92,  92,  96,  84],
       [ 81,  61,  75,  76,  73],
       [100,  71,  84,  58,  78],
       [100,  81,  62,  58,  66],
       [ 72,  94,  75,  90,  59],
       [ 98,  64,  75,  99,  94],
       [100,  63,  95,  73,  85],
       [ 96,  75,  84,  99,  75],
       [ 61,  94,  96,  57,  80],
       [ 50,  92,  90,  70,  50],
       [ 86,  85,  95,  79,  87],
       [ 87,  57,  82,  79,  63],
       [ 92, 100,  83,  92,  74],
       [ 75,  97,  72, 100,  66],
       [ 92,  66,  55,  91,  89],
       [ 75,  68,  90,  60,  99],
       [ 89,  75,  71,  79,  81],
       [ 67,  71,  70,  85,  79],
       [ 95,  64,  55, 100,  63],
       [ 56,  82,  97,  87,  67],
       [ 76,  60,  81,  75,  92],
       [ 64,  81,  53,  98,  75],
       [ 88,  74,  94,  83,  85],
       [ 65,  

In [8]:
students[0,0]
students[0:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[72, 84, 86, 94, 55],
       [70, 91, 86, 77, 75]])

In [10]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([ 55,  75,  61,  50,  65,  71,  84,  73,  78,  66,  59,  94,  85,
        75,  80,  50,  87,  63,  74,  66,  89,  99,  81,  79,  63,  67,
        92,  75,  85,  89,  74,  96,  96,  61,  95, 100,  87,  68,  80,
        78,  68,  92,  79,  98,  75,  88,  72,  91,  94,  58])

In [16]:
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分
np.sum(students[:],axis=1) #全班每位學生的總分
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([79. , 74.5, 78. , 79. , 78. ])